name: EconomyRepair
version: 1.0.0
main: land.face.repair.EconRepairPlugin
author: Faceguy
description: Allows item fixing based on level and maybe eventually rarity
api-version: 1.16
softdepend: [HolographicDisplays]
depend: [Facecore]

commands:
  repair:
    usage: /<command>
    aliases: [econrepair]
    description: Opens a repair GUI