name: SnaazyParties
version: 1.0
main: land.face.SnazzyPartiesPlugin
author: Faceguy
description: GO SHAWDY
api-version: 1.14

commands:
  genericbutlonger:
    usage: /<command>
    aliases: [generic]
    permission: generic.use
    description: its ya birfday